# Generated by Django 3.0.3 on 2020-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
        ),
    ]
